import React from 'react'
import Link from 'next/link'
export const metadata = {
    title: "next_13 about",
    description: "Generated by create next app",
  };
  
const AboutPage = () => {
  return (
    <div> 
        <h2>
        this is my about page
        </h2>  
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. In debitis placeat et nihil laboriosam quos sint quis. A, neque perspiciatis!</p>
        <Link href='/'>Home page</Link>
        </div>

  )
}
export default AboutPage;