import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "next_13 Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
